services:
  api:
    build: ./backend
    container_name: api_container
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - my_network

  landing:
    build: ./frontend_react
    container_name: landing_container
    ports:
      - "3000:3000"
    networks:
      - my_network

  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
