name: danielsanchez04
services:
  db: 
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: contact_form
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
  api:
    build: ./backend
    container_name: api_container
    ports:
      - "3227:3227"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - my_network

  landing:
    build: ./frontend_react
    container_name: landing_container
    ports:
      - "3240:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
