version: "3.8"

services:
  api:
    build: ./backend
    container_name: api_container
    ports:
      - "4000:4000"
    env_file: .env
    networks:
      - my_network

  landing:
    build: ./frontend_react
    container_name: landing_container
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
